### PR TITLE
Don't build the parameter type name manually

### LINKED ISSUE #6: Page actions with nullable arguments result in page compilation error
Following results in error: `'Nullable': static types cannot be used as type arguments`

``` c#
@functions {
    public void OnGet(int? id) {
        
    }
}
```

### PR DESCRIPTION
**Pull request by DamianEdwards**
This fixes #6

### CODE REVIEW

**Comment by rynowak** [comment]
:shipit: - will also look for similar usages since this likely would break with generics in those places

**Comment by DamianEdwards** [comment]
K, you going to merge this or just fix it?

**Comment by rynowak** [comment]
f2fd28e515df52683225205434a99d16183f0d2e

**Comment by rynowak** [comment]
sorry, @javiercn had a cool question about interface reimplmentation

**Pull request closed without merging**
